export const pillars = ['Empresa', 'Pessoas', 'Equipamentos'] as const;
export type Pillar = (typeof pillars)[number];
export type TaskKind = 'group' | 'task' | 'milestone';

export const STANDARD_TEMPLATE_VERSION = '2026-09-21-v3';

type SeedRow = [
  pillar: Pillar,
  item: string,
  title: string,
  owner?: string,
  parent?: string,
  kind?: TaskKind,
  durationDays?: number,
  predecessorItem?: string,
];

// Fonte: Cronograma Padrão Makro - Copia (1).xlsx, com a numeração
// hierárquica regularizada para atividades e subtarefas.
const rows: SeedRow[] = [
  ['Empresa', '1.1', 'ALINHAMENTO INTERNO', '', '', 'group'],
  [
    'Empresa',
    '1.1.1',
    'Realiza kickoff interno com áreas interessadas',
    'Comercial',
    '1.1',
  ],
  ['Empresa', '1.1.2', 'Reunião de Kickoff com cliente', 'Operação', '1.1'],
  [
    'Empresa',
    '1.2',
    'Abertura de chamados pela operação, de acordo com o planejado (terceiros, frotas, pessoas)',
    'Operação',
  ],
  ['Empresa', '1.3', 'Criação de acesso ao portal do cliente', 'CDI'],
  ['Empresa', '1.4', 'Documentação - Cadastrar empresa', 'CDI', '', 'group'],
  ['Empresa', '1.4.1', 'CND Estadual', 'CDI', '1.4'],
  ['Empresa', '1.4.2', 'CND Municipal', 'CDI', '1.4'],
  ['Empresa', '1.4.3', 'Cartão CNPJ', 'CDI', '1.4'],
  ['Empresa', '1.4.4', 'Contrato Social + Alterações', 'CDI', '1.4'],
  ['Empresa', '1.4.5', 'FISPQS', 'CDI', '1.4'],
  ['Empresa', '1.4.6', 'Inspeção do Trabalho', 'CDI', '1.4'],
  ['Empresa', '1.4.7', 'Procedimento de atividade', 'CDI', '1.4'],
  ['Empresa', '1.4.8', 'Seguro de Responsabilidade Civil', 'CDI', '1.4'],
  ['Empresa', '1.4.9', 'ARP/AR', 'CDI', '1.4'],
  ['Empresa', '1.4.10', 'Alvará de Funcionamento', 'CDI', '1.4'],
  ['Empresa', '1.4.11', 'LTCAT', 'CDI', '1.4'],
  ['Empresa', '1.4.12', 'CND Federal', 'CDI', '1.4'],
  ['Empresa', '1.4.13', 'CND Trabalhista', 'CDI', '1.4'],
  [
    'Empresa',
    '1.5',
    'Documentação - Programas de Segurança',
    'SMS',
    '',
    'group',
  ],
  [
    'Empresa',
    '1.5.1',
    'Elaborar Programa de Segurança (PGR / PCMSO)',
    'SMS',
    '1.5',
  ],
  [
    'Empresa',
    '1.5.2',
    'Postar Programa de Segurança (PGR / PCMSO)',
    'CDI',
    '1.5',
  ],
  [
    'Empresa',
    '1.5.3',
    'Confirmar liberação do Programa de Segurança (PGR / PCMSO)',
    'CDI',
    '1.5',
  ],
  ['Empresa', '1.6', 'CONTRATAÇÃO DE TERCEIROS', '', '', 'group'],
  [
    'Empresa',
    '1.6.1',
    'Diretoria aprovar a necessidade de sublocação ou não',
    'Diretoria de Operações',
    '1.6',
  ],
  [
    'Empresa',
    '1.6.2',
    'Diretoria assina via Totvs Sing',
    'Diretoria de Operações',
    '1.6',
  ],
  ['Empresa', '1.6.3', 'Abertura de chamado CSM', 'Operação', '1.6'],
  [
    'Empresa',
    '1.6.4',
    'Suprimentos realiza cotações no mercado',
    'Suprimentos',
    '1.6',
  ],
  [
    'Empresa',
    '1.6.5',
    'Margem é analisada e retorna ao suprimentos',
    'Suprimentos',
    '1.6',
  ],
  ['Empresa', '1.6.6', 'Contrato assinado pelo jurídico', 'Suprimentos', '1.6'],
  [
    'Empresa',
    '1.6.7',
    'Assinatura de contrato (Diretor de Operações, Suprimentos, Gerente da unidade e fornecedor)',
    'Suprimentos',
    '1.6',
  ],
  ['Empresa', '1.6.8', 'Envio de documentação de terceiros', 'CDI', '1.6'],
  ['Empresa', '1.6.9', 'Aprovação de documentação pelo cliente', 'CDI', '1.6'],
  [
    'Pessoas',
    '2.1',
    'Documentação - Colaboradores',
    'Gente e Gestão',
    '',
    'group',
  ],
  ['Pessoas', '2.1.1', 'Postar book de documentação de pessoas', 'CDI', '2.1'],
  ['Pessoas', '2.1.2', 'Aprovação de documentação pelo cliente', 'CDI', '2.1'],
  [
    'Pessoas',
    '2.2',
    'Contratação de novos colaboradores',
    'Gente e Gestão',
    '',
    'group',
  ],
  ['Pessoas', '2.2.1', 'Processo Seletivo', 'Gente e Gestão', '2.2'],
  ['Pessoas', '2.2.2', 'Admissão', 'DP', '2.2'],
  [
    'Pessoas',
    '2.3',
    'Integração / Crachá dos novos colaboradores',
    'Gente e Gestão',
  ],
  ['Pessoas', '2.4', 'Treinamentos', 'SMS', '', 'group'],
  ['Pessoas', '2.4.1', 'Treinamentos Makro', 'SMS', '2.4'],
  ['Pessoas', '2.4.2', 'Treinamentos Específicos Cliente', 'SMS', '2.4'],
  ['Pessoas', '2.5', 'APOIO À MOBILIZAÇÃO', '', '', 'group'],
  ['Pessoas', '2.5.1', 'Hospedagem', 'Suprimentos', '2.5'],
  ['Pessoas', '2.5.2', 'Alimentação', 'Suprimentos', '2.5'],
  ['Pessoas', '2.5.3', 'EPI e Fardamentos', 'Suprimentos', '2.5', 'group'],
  ['Pessoas', '2.5.3.1', 'Compra de Fardamentos', 'Suprimentos', '2.5.3'],
  ['Pessoas', '2.5.3.2', 'Entrega dos Fardamentos', 'SMS', '2.5.3'],
  ['Pessoas', '2.5.3.3', "Compra de EPI's", 'Suprimentos', '2.5.3'],
  ['Pessoas', '2.5.3.4', "Entrega de EPI's", 'SMS', '2.5.3'],
  ['Pessoas', '2.5.4', 'Emissão de passagens', 'Operação', '2.5'],
  ['Equipamentos', '3.1', 'Plano de Rigging', 'Técnica'],
  ['Equipamentos', '3.2', 'ART do Plano de Rigging', 'Engenharia'],
  ['Equipamentos', '3.3', 'FROTAS E ACESSÓRIOS', '', '', 'group'],
  [
    'Equipamentos',
    '3.3.1',
    'Mapear disponibilidade dos equipamentos',
    'Operação',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.2',
    'Liberar equipamento do contrato anterior',
    'Operação',
    '3.3',
  ],
  ['Equipamentos', '3.3.3', 'Liberar de manutenção', 'Manutenção', '3.3'],
  [
    'Equipamentos',
    '3.3.4',
    'Logística para transferência de unidade',
    'Transportes',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.4.1',
    'Elaborar plano de transporte',
    'Técnica',
    '3.3.4',
  ],
  [
    'Equipamentos',
    '3.3.4.2',
    'Elaborar planejamento de transporte (MKT)',
    'Transportes',
    '3.3.4',
  ],
  [
    'Equipamentos',
    '3.3.4.3',
    'Emitir licenças de transportes',
    'Transportes',
    '3.3.4',
  ],
  ['Equipamentos', '3.3.4.4', 'Emissão de AET', 'Transportes', '3.3.4'],
  [
    'Equipamentos',
    '3.3.4.5',
    'Realizar Transporte de acessórios (contrapesos, TY, jib, moitão, etc.)',
    'Transportes',
    '3.3.4',
  ],
  [
    'Equipamentos',
    '3.3.5',
    'Verificar plano de manutenção preventiva em dia',
    'Manutenção',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.6',
    'Inspecionar e providenciar acessórios (ganchos, moitões, estropos, cabos, cintas)',
    'Engenharia',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.6.1',
    'Materiais de Içamento',
    'Operação',
    '3.3.6',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.6.1.1',
    'Compra de Materiais de Içamento',
    'Suprimentos',
    '3.3.6.1',
  ],
  [
    'Equipamentos',
    '3.3.6.1.2',
    'Separação de Materiais de Içamento',
    'Operação',
    '3.3.6.1',
  ],
  [
    'Equipamentos',
    '3.3.6.2',
    'Materiais de Patolamento',
    'Operação',
    '3.3.6',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.6.2.1',
    'Compra de Materiais de Patolamento',
    'Suprimentos',
    '3.3.6.2',
  ],
  [
    'Equipamentos',
    '3.3.6.2.2',
    'Separação de Materiais de Patolamento',
    'Operação',
    '3.3.6.2',
  ],
  [
    'Equipamentos',
    '3.3.7',
    'Book completo de engenharia',
    'Engenharia',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.7.1',
    'Laudo de inspeção técnica da frota',
    'Engenharia',
    '3.3.7',
  ],
  [
    'Equipamentos',
    '3.3.7.2',
    'Laudo de acessórios e materiais de içamento',
    'Engenharia',
    '3.3.7',
  ],
  ['Equipamentos', '3.3.7.3', 'Emissão da ART', 'Engenharia', '3.3.7'],
  [
    'Equipamentos',
    '3.3.8',
    'Regularização documental da frota (DETRAN, CRLV, AET)',
    'Ativos',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.9',
    'Logística para cliente',
    'Transportes',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.9.1',
    'Elaborar plano de transporte',
    'Transportes',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.9.2',
    'Elaborar planejamento de transporte (MKT)',
    'Transportes',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.9.3',
    'Emitir licenças de transportes',
    'Transportes',
    '3.3.9',
  ],
  ['Equipamentos', '3.3.9.4', 'Emissão de AET', 'Transportes', '3.3.9'],
  [
    'Equipamentos',
    '3.3.9.5',
    'Realizar Transporte de acessórios (contrapesos, TY, jib, moitão, etc.)',
    'Transportes',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.9.6',
    'Transferência de unidades do equipamento',
    'Transportes',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.10',
    'Postagem de documentação no portal do cliente',
    'CDI',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.11',
    'Aprovação de documentação pelo cliente',
    'CDI',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.12',
    'Agendar vistoria da frota no cliente',
    'Operação',
    '3.3',
  ],
  ['Equipamentos', '3.3.13', 'Montar equipamento', 'Operação', '3.3'],
  [
    'Equipamentos',
    '3.3.14',
    'Compra de Equipamentos',
    'Suprimentos',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.14.1',
    'Especificação Técnica pela Engenharia',
    'Engenharia',
    '3.3.14',
  ],
  [
    'Equipamentos',
    '3.3.14.2',
    'Aprovação da presidência para cotação de novos equipamentos',
    'Presidência',
    '3.3.14',
  ],
  ['Equipamentos', '3.3.14.3', 'Cotação no mercado', 'Suprimentos', '3.3.14'],
  [
    'Equipamentos',
    '3.3.14.4',
    'Compra de Equipamentos',
    'Suprimentos',
    '3.3.14',
  ],
  ['Equipamentos', '3.3.14.5', 'Entrega no cliente', 'MKT', '3.3.14'],
  ['Equipamentos', 'M.1', 'INÍCIO DA OPERAÇÃO', 'Operação', '', 'milestone', 0],
];

function taskId(item: string) {
  return `std-${item.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
}

export const defaultTemplateTasks = rows.map(
  (
    [
      pillar,
      item,
      title,
      owner = '',
      parent = '',
      kind = 'task',
      durationDays = 1,
      predecessorItem = '',
    ],
    index,
  ) => ({
    id: taskId(item),
    parentId: parent ? taskId(parent) : null,
    pillar,
    item,
    title,
    owner,
    durationDays: kind === 'group' ? 0 : durationDays,
    predecessorId: predecessorItem ? taskId(predecessorItem) : null,
    kind,
    sortOrder: (index + 1) * 10,
  }),
);

// Escopo padrão de mobilização, consolidado das abas Contrato, Frota,
// Mão de Obra, Inf. Legais e CFI do modelo de projeto.
const scopedRows: SeedRow[] = [
  ['Empresa', '1', 'CONTRATO', '', '', 'group'],
  ['Empresa', '1.1', 'Cadastrar identificação e vigência do contrato', 'Comercial', '1', 'task', 2],
  ['Empresa', '1.2', 'Confirmar prazo de mobilização e reunião de kickoff', 'Operação', '1', 'task', 2],
  ['Empresa', '1.3', 'Cadastrar responsáveis Makro e cliente', 'Comercial', '1', 'task', 2],
  ['Equipamentos', '2', 'FROTA', '', '', 'group'],
  ['Equipamentos', '2.1', 'Definir frota e data de início dos equipamentos', 'Operação', '2', 'task', 3],
  ['Equipamentos', '2.2', 'Validar plano de manutenção preventiva', 'Manutenção', '2', 'task', 2],
  ['Equipamentos', '2.3', 'Regularizar documentação da frota e acessórios', 'Engenharia', '2', 'task', 3],
  ['Pessoas', '3', 'MÃO DE OBRA', '', '', 'group'],
  ['Pessoas', '3.1', 'Dimensionar quadro de mão de obra e turnos', 'Gente e Gestão', '3', 'task', 2],
  ['Pessoas', '3.2', 'Conduzir processo seletivo e admissões', 'Gente e Gestão', '3', 'task', 5],
  ['Pessoas', '3.3', 'Programar integração, crachá e treinamentos', 'SMS', '3', 'task', 3],
  ['Empresa', '4', 'INFORMAÇÕES LEGAIS', '', '', 'group'],
  ['Empresa', '4.1', 'Consolidar documentos legais da Makro', 'CDI', '4', 'task', 3],
  ['Empresa', '4.2', 'Consolidar informações legais do cliente', 'CDI', '4', 'task', 2],
  ['Empresa', '4.3', 'Preparar programas legais e requisitos de segurança', 'SMS', '4', 'task', 4],
  ['Empresa', '5', 'CFI', '', '', 'group'],
  ['Empresa', '5.1', 'Definir composição do custo fixo indireto', 'Financeiro', '5', 'task', 3],
  ['Empresa', '5.2', 'Validar veículos de apoio e vinculação à frota', 'Operação', '5', 'task', 2],
  ['Empresa', '5.3', 'Consolidar observações e premissas do CFI', 'Financeiro', '5', 'task', 2],
  ['Empresa', 'M.1', 'INÍCIO DA OPERAÇÃO', 'Operação', '', 'milestone', 0],
];

export const projectScopeTemplateTasks = scopedRows.map(
  ([pillar, item, title, owner = '', parent = '', kind = 'task', durationDays = 1, predecessorItem = ''], index) => ({
    id: taskId(`scope-${item}`), parentId: parent ? taskId(`scope-${parent}`) : null, pillar, item, title, owner,
    durationDays: kind === 'group' ? 0 : durationDays,
    predecessorId: predecessorItem ? taskId(`scope-${predecessorItem}`) : null,
    kind, sortOrder: (index + 1) * 10,
  }),
);
