export const pillars = ['Empresa', 'Pessoas', 'Equipamentos'] as const;
export type Pillar = (typeof pillars)[number];
export type TaskKind = 'group' | 'task' | 'milestone';

type SeedRow = [Pillar, string, string, string?, string?, TaskKind?];

const rows: SeedRow[] = [
  ['Empresa', '1.1', 'ALINHAMENTO INTERNO', '', '', 'group'],
  [
    'Empresa',
    '1.1.1',
    'Informa as áreas sobre projeto',
    'Executivo Comercial',
    '1.1',
  ],
  [
    'Empresa',
    '1.1.2',
    'Preenchimento de Sheets de planejamento',
    'Backlog Comercial',
    '1.1',
  ],
  [
    'Empresa',
    '1.1.3',
    'Realiza kickoff interno com áreas interessadas',
    'Backlog Comercial',
    '1.1',
  ],
  [
    'Empresa',
    '1.1.4',
    'Reunião de Kickoff com cliente',
    'Executivo Comercial',
    '1.1',
  ],
  [
    'Empresa',
    '1.2',
    'Abertura de chamados pela operação, de acordo com o planejado (terceiros, frotas, pessoas)',
    'Operação',
  ],
  ['Empresa', '1.3', 'Criação de acesso ao portal do cliente', 'CDI'],
  ['Empresa', '1.4', 'Documentação - Cadastrar empresa', 'CDI', '', 'group'],
  ['Empresa', '1.4.1', 'CND Estadual', 'CDI', '1.4'],
  ['Empresa', '1.4.2', 'CND Municipal', 'CDI', '1.4'],
  ['Empresa', '1.4.3', 'Cartão CNPJ', 'CDI', '1.4'],
  ['Empresa', '1.4.4', 'Contrato Social + Alterações', 'CDI', '1.4'],
  ['Empresa', '1.4.5', 'FISPQS', 'CDI', '1.4'],
  ['Empresa', '1.4.6', 'Inspeção do Trabalho', 'CDI', '1.4'],
  ['Empresa', '1.4.7', 'Procedimento de atividade', 'CDI', '1.4'],
  ['Empresa', '1.4.8', 'Seguro de Responsabilidade Civil', 'CDI', '1.4'],
  ['Empresa', '1.4.9', 'ARP/AR', 'CDI', '1.4'],
  ['Empresa', '1.4.10', 'Alvará de Funcionamento', 'CDI', '1.4'],
  ['Empresa', '1.4.11', 'LTCAT', 'CDI', '1.4'],
  ['Empresa', '1.4.12', 'CND Federal', 'CDI', '1.4'],
  ['Empresa', '1.4.13', 'CND Trabalhista', 'CDI', '1.4'],
  [
    'Empresa',
    '1.5',
    'Documentação - Programas de Segurança',
    'Raniere',
    '',
    'group',
  ],
  [
    'Empresa',
    '1.5.1',
    'Elaborar Programa de Segurança (PGR / PCMSO)',
    'SMS / Cred',
    '1.5',
  ],
  [
    'Empresa',
    '1.5.2',
    'Postar Programa de Segurança (PGR / PCMSO)',
    'Marla',
    '1.5',
  ],
  [
    'Empresa',
    '1.5.3',
    'Confirmar liberação do Programa de Segurança (PGR / PCMSO)',
    'Cliente',
    '1.5',
  ],
  ['Empresa', '1.6', 'CONTRATAÇÃO DE TERCEIROS', '', '', 'group'],
  [
    'Empresa',
    '1.6.1',
    'Diretoria aprovar a necessidade de sublocação ou não',
    'Diretoria',
    '1.6',
  ],
  ['Empresa', '1.6.2', 'Diretoria assina via Totvs Sing', 'Diretoria', '1.6'],
  ['Empresa', '1.6.3', 'Abertura de chamado CSM', 'Operação', '1.6'],
  [
    'Empresa',
    '1.6.4',
    'Suprimentos realiza cotações no mercado',
    'Suprimentos',
    '1.6',
  ],
  [
    'Empresa',
    '1.6.5',
    'Margem é analisada e retorna ao suprimentos',
    'Suprimentos',
    '1.6',
  ],
  ['Empresa', '1.6.6', 'Contrato assinado pelo jurídico', 'Suprimentos', '1.6'],
  [
    'Empresa',
    '1.6.7',
    'Assinatura de contrato (Diretor de Operações, Suprimentos, Gerente da unidade e fornecedor)',
    'Suprimentos',
    '1.6',
  ],
  ['Empresa', '1.6.8', 'Envio de documentação de terceiros', 'CDI', '1.6'],
  ['Empresa', '1.6.9', 'Aprovação de documentação pelo cliente', 'CDI', '1.6'],
  ['Pessoas', '2.1', 'Documentação - Colaboradores', 'CDI', '', 'group'],
  ['Pessoas', '2.1.1', 'Postar book de documentação de pessoas', 'CDI', '2.1'],
  ['Pessoas', '2.1.2', 'Aprovação de documentação pelo cliente', 'CDI', '2.1'],
  ['Pessoas', '2.2', 'Contratação de novos colaboradores', 'DP / RH'],
  ['Pessoas', '2.3', 'Integração / Crachá dos novos colaboradores', 'DP / RH'],
  ['Pessoas', '2.4', 'Treinamentos específicos', 'Operação'],
  ['Pessoas', '2.5', 'Definir operador', 'Operação'],
  ['Pessoas', '2.6', 'Definir sinaleiro', 'Operação'],
  ['Pessoas', '2.7', 'Definir equipe de apoios', 'Operação'],
  ['Pessoas', '2.8', 'APOIO À MOBILIZAÇÃO', '', '', 'group'],
  ['Pessoas', '2.8.1', 'Reserva de hospedagem', 'Suprimentos', '2.8'],
  ['Pessoas', '2.8.2', 'Fechar alimentação', 'Suprimentos', '2.8'],
  ['Pessoas', '2.8.3', 'EPI e Fardamentos', 'Suprimentos', '2.8'],
  ['Pessoas', '2.8.4', 'Compra de Uniformes', 'Suprimentos', '2.8'],
  ['Pessoas', '2.8.5', 'Emissão de passagens', 'Suprimentos', '2.8'],
  ['Equipamentos', '3.1', 'Plano de Rigging', 'Técnica'],
  ['Equipamentos', '3.2', 'ART do Plano de Rigging', 'Engenharia'],
  ['Equipamentos', '3.3', 'FROTAS E ACESSÓRIOS', '', '', 'group'],
  [
    'Equipamentos',
    '3.3.1',
    'Mapear disponibilidade dos equipamentos',
    'Operação / CCO',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.2',
    'Liberar equipamento do contrato anterior',
    'Operação',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.3',
    'Liberar de manutenção (caso possua pendência)',
    'Manutenção',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.4',
    'Logística para transferência de unidade',
    'Logística',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.4.1',
    'Elaborar plano de transporte',
    'Logística',
    '3.3.4',
  ],
  [
    'Equipamentos',
    '3.3.4.2',
    'Elaborar planejamento de transporte (MKT)',
    'Logística',
    '3.3.4',
  ],
  [
    'Equipamentos',
    '3.3.4.3',
    'Emitir licenças de transportes',
    'Logística',
    '3.3.4',
  ],
  ['Equipamentos', '3.3.4.4', 'Emissão de AET', 'Logística', '3.3.4'],
  [
    'Equipamentos',
    '3.3.4.5',
    'Realizar transporte de acessórios (contrapesos, TY, jib, moitão etc.)',
    'Logística',
    '3.3.4',
  ],
  [
    'Equipamentos',
    '3.3.4.6',
    'Transferência de unidades do equipamento',
    'Logística',
    '3.3.4',
  ],
  [
    'Equipamentos',
    '3.3.5',
    'Verificar plano de manutenção preventiva em dia',
    'Manutenção',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.6',
    'Inspecionar e providenciar acessórios (ganchos, moitões, estropos, cabos e cintas)',
    'Engenharia',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.6.1',
    'Separação de Materiais de Içamento',
    'Operação',
    '3.3.6',
  ],
  [
    'Equipamentos',
    '3.3.6.2',
    'Separação de Materiais de Patolamento',
    'Operação',
    '3.3.6',
  ],
  [
    'Equipamentos',
    '3.3.7',
    'Book completo de engenharia',
    'Engenharia',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.7.1',
    'Laudo de inspeção técnica da frota',
    'Engenharia',
    '3.3.7',
  ],
  [
    'Equipamentos',
    '3.3.7.2',
    'Laudo de acessórios e materiais de içamento',
    'Engenharia',
    '3.3.7',
  ],
  ['Equipamentos', '3.3.7.3', 'Emissão da ART', 'Engenharia', '3.3.7'],
  [
    'Equipamentos',
    '3.3.8',
    'Regularização documental da frota (DETRAN, CRLV, AET)',
    'Ativos',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.9',
    'Logística para cliente',
    'Logística',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.9.1',
    'Elaborar plano de transporte',
    'Logística',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.9.2',
    'Elaborar planejamento de transporte (MKT)',
    'Logística',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.9.3',
    'Emitir licenças de transportes',
    'Logística',
    '3.3.9',
  ],
  ['Equipamentos', '3.3.9.4', 'Emissão de AET', 'Logística', '3.3.9'],
  [
    'Equipamentos',
    '3.3.9.5',
    'Realizar transporte de acessórios (contrapesos, TY, jib, moitão etc.)',
    'Logística',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.9.6',
    'Transferência de unidades do equipamento',
    'Logística',
    '3.3.9',
  ],
  [
    'Equipamentos',
    '3.3.10',
    'Postagem de documentação no portal do cliente',
    'CDI / Unidade',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.11',
    'Aprovação de documentação pelo cliente',
    'Cliente',
    '3.3',
  ],
  [
    'Equipamentos',
    '3.3.12',
    'Agendar vistoria da frota no cliente',
    'Operação',
    '3.3',
  ],
  ['Equipamentos', '3.3.13', 'Montar equipamento', 'Operação', '3.3'],
  [
    'Equipamentos',
    '3.3.14',
    'Compra de Equipamentos',
    'Operação',
    '3.3',
    'group',
  ],
  [
    'Equipamentos',
    '3.3.14.1',
    'Especificação Técnica pela Engenharia',
    'Engenharia',
    '3.3.14',
  ],
  [
    'Equipamentos',
    '3.3.14.2',
    'Aprovação da presidência para cotação de novos equipamentos',
    'Presidência',
    '3.3.14',
  ],
  ['Equipamentos', '3.3.14.3', 'Cotação no mercado', 'Suprimentos', '3.3.14'],
  [
    'Equipamentos',
    '3.3.14.4',
    'Compra de Equipamentos',
    'Suprimentos',
    '3.3.14',
  ],
  ['Equipamentos', '3.3.14.5', 'Entrega no cliente', 'MKT', '3.3.14'],
  ['Empresa', 'M.1', 'Início de operação', 'Operação', '', 'milestone'],
];

function taskId(item: string) {
  return `std-${item.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
}

export const defaultTemplateTasks = rows.map(
  ([pillar, item, title, owner = '', parent = '', kind = 'task'], index) => ({
    id: taskId(item),
    parentId: parent ? taskId(parent) : null,
    pillar,
    item,
    title,
    owner,
    durationDays: kind === 'group' ? 0 : 1,
    kind,
    sortOrder: (index + 1) * 10,
  }),
);
